### ISSUE TITLE
About KeyError

### ISSUE THREAD

**Issue by jiaruHithub** [carrierlxk/AGNN#7]
The Error is

Traceback (most recent call last):
  File "test_iteration_conf_gnn.py", line 185, in <module>
    main()
  File "test_iteration_conf_gnn.py", line 136, in main
    for index, batch in enumerate(testloader):
  File "D:\lib\site-packages\torch\utils\data\dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\lib\site-packages\torch\utils\data\dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\muqian\code\AGNN\dataloaders\PairwiseImg_test_new.py", line 115, in __getitem__
    my_index = self.Index[seq_name1]
KeyError: '480p'

i don't know how to tackle it.Please help me.Thank you very mach.

**Comment by jiaruHithub** [comment]
I found a method that to use'dict.setdefault'add a index to self.Index a np.array.
Then I can run thr code with no error
